import { getActionType, getSagaActionType, createAsyncActionTypes } from './utils';


// ActionTypes builders
export const APPLICATION_CHANGE_ROUTE = 'APPLICATION_CHANGE_ROUTE';
export const APPLICATION_ROUTE_ERROR = 'APPLICATION_ROUTE_ERROR';
export const APPLICATION_DRAWER_TRIGGER = getActionType('APPLICATION_DRAWER_TRIGGER');
export const APPLICATION_LOCALE_SET = 'APPLICATION_LOCALE_SET';
export const APPLICATION_MOBILE_BREAKPOINT_SET = 'APPLICATION_MOBILE_BREAKPOINT_SET';
export const APPLICATION_PAGE_WIDTH_CHANGED = 'APPLICATION_PAGE_WIDTH_CHANGED';
export const APPLICATION_POST_NOTIFICATION = 'APPLICATION_POST_NOTIFICATION';
export const APPLICATION_POP_NOTIFICATION = 'APPLICATION_POP_NOTIFICATION';
export const APPLICATION_PAGE_LOADING_TRIGGER = 'APPLICATION_PAGE_LOADING_TRIGGER';
