
export const CHECKOUT_CREATE = 'CHECKOUT_CREATE';
export const CHECKOUT_CREATE_SUCCESS = 'CHECKOUT_CREATE_SUCCESS';
export const CHECKOUT_CREATE_ERROR = 'CHECKOUT_CREATE_ERROR';

export const CHECKOUT_SET_PAYMENT_OPTIONS = 'CHECKOUT_SET_PAYMENT_OPTIONS';

export const CHECKOUT_UPDATE = 'CHECKOUT_UPDATE';
export const CHECKOUT_UPDATE_SUCCESS = 'CHECKOUT_UPDATE_SUCCESS';
export const CHECKOUT_UPDATE_ERROR = 'CHECKOUT_UPDATE_ERROR';
