
// All Collections
export const COLLECTIONS = 'COLLECTIONS';
export const COLLECTIONS_SUCCESS = 'COLLECTIONS_SUCCESS';
export const COLLECTIONS_ERROR = 'COLLECTIONS_ERROR';

// Collections list
export const COLLECTIONS_FIND = 'COLLECTIONS_FIND';
export const COLLECTIONS_FIND_SUCCESS = 'COLLECTIONS_FIND_SUCCESS';
export const COLLECTIONS_FIND_ERROR = 'COLLECTIONS_FIND_ERROR';

// Add collection
export const COLLECTIONS_ADD = 'COLLECTIONS_ADD';
export const COLLECTIONS_ADD_SUCCESS = 'COLLECTIONS_ADD_SUCCESS';
export const COLLECTIONS_ADD_ERROR = 'COLLECTIONS_ADD_ERROR';

// Fetch item
export const COLLECTIONS_ITEM = 'COLLECTIONS_ITEM';
export const COLLECTIONS_ITEM_SUCCESS = 'COLLECTIONS_ITEM_SUCCESS';
export const COLLECTIONS_ITEM_ERROR = 'COLLECTIONS_ITEM_ERROR';

// Save item
export const COLLECTIONS_ITEM_SAVE = 'COLLECTIONS_ITEM_SAVE';
export const COLLECTIONS_ITEM_SAVE_SUCCESS = 'COLLECTIONS_ITEM_SAVE_SUCCESS';
export const COLLECTIONS_ITEM_SAVE_ERROR = 'COLLECTIONS_ITEM_SAVE_ERROR';

// Bulk updates
export const COLLECTIONS_BULK_SAVE = 'COLLECTIONS_BULK_SAVE';
export const COLLECTIONS_BULK_SAVE_SUCCESS = 'COLLECTIONS_BULK_SAVE_SUCCESS';
export const COLLECTIONS_BULK_SAVE_ERROR = 'COLLECTIONS_BULK_SAVE_ERROR';

// Update featured in homepage
export const COLLECTIONS_HOMEPAGE_FEATURED_UPDATE = 'COLLECTIONS_HOMEPAGE_FEATURED_UPDATE';
export const COLLECTIONS_HOMEPAGE_FEATURED_UPDATE_SUCCESS = 'COLLECTIONS_HOMEPAGE_FEATURED_UPDATE_SUCCESS';
export const COLLECTIONS_HOMEPAGE_FEATURED_UPDATE_ERROR = 'COLLECTIONS_HOMEPAGE_FEATURED_UPDATE_ERROR';
