
// Contents list
export const CONTENTS_FIND = 'CONTENTS_FIND';
export const CONTENTS_FIND_SUCCESS = 'CONTENTS_FIND_SUCCESS';
export const CONTENTS_FIND_ERROR = 'CONTENTS_FIND_ERROR';

// Add content
export const CONTENTS_ADD = 'CONTENTS_ADD';
export const CONTENTS_ADD_SUCCESS = 'CONTENTS_ADD_SUCCESS';
export const CONTENTS_ADD_ERROR = 'CONTENTS_ADD_ERROR';

// Fetch item
export const CONTENTS_ITEM = 'CONTENTS_ITEM';
export const CONTENTS_ITEM_SUCCESS = 'CONTENTS_ITEM_SUCCESS';
export const CONTENTS_ITEM_ERROR = 'CONTENTS_ITEM_ERROR';

// Save item
export const CONTENTS_ITEM_SAVE = 'CONTENTS_ITEM_SAVE';
export const CONTENTS_ITEM_SAVE_SUCCESS = 'CONTENTS_ITEM_SAVE_SUCCESS';
export const CONTENTS_ITEM_SAVE_ERROR = 'CONTENTS_ITEM_SAVE_ERROR';

// Bulk save
export const CONTENTS_BULK_SAVE = 'CONTENTS_BULK_SAVE';
export const CONTENTS_BULK_SAVE_SUCCESS = 'CONTENTS_BULK_SAVE_SUCCESS';
export const CONTENTS_BULK_SAVE_ERROR = 'CONTENTS_BULK_SAVE_ERROR';
