
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_ERROR';

export const ORDER_CLEAR = 'ORDER_CLEAR';

export const ORDERS_FIND = 'ORDERS_FIND';
export const ORDERS_FIND_SUCCESS = 'ORDERS_FIND_SUCCESS';
export const ORDERS_FIND_ERROR = 'ORDERS_FIND_ERROR';

export const ORDERS_ITEM = 'ORDERS_ITEM';
export const ORDERS_ITEM_SUCCESS = 'ORDERS_ITEM_SUCCESS';
export const ORDERS_ITEM_ERROR = 'ORDERS_ITEM_ERROR';

export const ORDERS_UPDATE = 'ORDERS_UPDATE';
export const ORDERS_UPDATE_SUCCESS = 'ORDERS_UPDATE_SUCCESS';
export const ORDERS_UPDATE_ERROR = 'ORDERS_UPDATE_ERROR';

export const ORDERS_SEND_EMAIL = 'ORDERS_SEND_EMAIL';
export const ORDERS_SEND_EMAIL_SUCCESS = 'ORDERS_SEND_EMAIL_SUCCESS';
export const ORDERS_SEND_EMAIL_ERROR = 'ORDERS_SEND_EMAIL_ERROR';

